version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Generate static site
          command: yarn build
      - run:
          name: Deploy
          command: |
            cd dist
            git init
            git config --local user.name "gplane"
            git config --local user.email "g-plane@hotmail.com"
            git add -A
            git commit -m "Blog updated at `date +"%Y-%m-%d %H:%M:%S"`"
            git push https://gplane:$coding_token@git.coding.net/gplane/gplane.coding.me.git master --force
